name: finity_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  cloud_functions: ^5.6.1
  intl: ^0.20.2
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cliq.png
    - assets/images/netflix.png
    - assets/images/spotify.png
    - assets/images/shahid.png
    - assets/images/arab_bank.png
    - assets/images/zain.jpg
    - assets/images/default.png
