// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1IQNnf86ykK1i23B-Mtiz6_Q1bvGlis',
    appId: '1:58311186110:web:197a5af53137eccaedb0ef',
    messagingSenderId: '58311186110',
    projectId: 'finity-db2d9',
    authDomain: 'finity-db2d9.firebaseapp.com',
    storageBucket: 'finity-db2d9.firebasestorage.app',
    measurementId: 'G-2VF4SH2Y6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzL-6vcYiq-Z_wqiIpREH0pKFoeHuTgFo',
    appId: '1:58311186110:android:7a260755affea29eedb0ef',
    messagingSenderId: '58311186110',
    projectId: 'finity-db2d9',
    storageBucket: 'finity-db2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZCD3mh6PJES_J-bbb0bs8Ynb_jy4N7OM',
    appId: '1:58311186110:ios:c2018a8f80f48c49edb0ef',
    messagingSenderId: '58311186110',
    projectId: 'finity-db2d9',
    storageBucket: 'finity-db2d9.firebasestorage.app',
    iosBundleId: 'com.example.finity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZCD3mh6PJES_J-bbb0bs8Ynb_jy4N7OM',
    appId: '1:58311186110:ios:c2018a8f80f48c49edb0ef',
    messagingSenderId: '58311186110',
    projectId: 'finity-db2d9',
    storageBucket: 'finity-db2d9.firebasestorage.app',
    iosBundleId: 'com.example.finity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1IQNnf86ykK1i23B-Mtiz6_Q1bvGlis',
    appId: '1:58311186110:web:df7299c228b2b251edb0ef',
    messagingSenderId: '58311186110',
    projectId: 'finity-db2d9',
    authDomain: 'finity-db2d9.firebaseapp.com',
    storageBucket: 'finity-db2d9.firebasestorage.app',
    measurementId: 'G-437X48PHZG',
  );
}
